### ISSUE TITLE
PHP 8.0 porting status

### ISSUE THREAD

**Issue by glensc** [zf1s/zf1#51]
List of documented backward-incompatible changes:
- https://www.php.net/manual/en/migration80.incompatible.php

# Tasks
- [x] PHP 8.0 compatibility patch: #32
  - [x] Fix a bug in Zend_Date for PHP 8.0 #62
  - [x] Missing default values caused errorHandlerIgnore to fail under PHP 8.0, #63
  - [x] Guard file_exists call to prevent fatal error, #64
  - [x] Remove libxml deprecations for php 8.0, #65
  - [x] Do not pass &$parts as reference to resolvePharParentPath, #67
  - [x] Ensure non-negative values for bcmath, #68
  - [x] Add support for gd resource type change in php 8.0, #69
  - [x] Add guard on fclose in Zend_Mail_Storage_Mbox, #70
  - [x] Implement T_NAME_QUALIFIED token in ClassFileLocation for php 8.0, #71
  - [x] Remove openssl deprecation for php 8.0, #73
  - [x] php 8.0: Change call in ClassMapAutoloader to preserve original behaviour, #74
  - [x] Make Zend_Validate_Date work as expected under PHP 8.0, #75
  - [x] Fixed reflection deprecations for php 8.0, #76
  - [x] Small fixes for tests in favor of PHP 8.0 compat, #77
  - [x] Remove default values from method signatures, #78
  - [x] Fix vsprintf TypeError for php 8.0, #79
  - [x] Enforce types for PHP 8.0, #80
  - [x] Fix Zend_Form_ElementTest, #81
  - [x] Fix iterators usage, #82
  - [x] DB2 constants are missing when setting up db factory, #83
  - [x] Catch ValueError on PHP 8.0 for Pdo Statement #85
- [x] Remove usage of $php_errormsg: #35, #42
- [x] version_compare does not support `gte`: https://github.com/zf1s/zf1/issues/51#issuecomment-772469392, https://github.com/zf1s/zf1/pull/26
- [x] iconv_substr behaves differently under PHP 8: #31
- [x] Zend_Log: catch TypeError/ValueError for PHP 8.0, #88
- [x] Fix error handler for PHP8 usage #99
- [x] Fix Zend_Db issues with php8 #106
- [x] php8 Zend_Log compatibility fixes #107
- [x] [zend-paginator] prevent fatal error on php8 #109
- [x] [zend-queue] prevent TypeError on md5 of non-string message #110 
- [x] [zend-loader] refactor broken resolvePharParentPath static method #111

**Comment by glensc** [comment]
# PHP 8.x version_compare error

- https://github.com/Shardj/zf1-future/issues/128

Either one of these happens:
1. we can pick their patch
2. (if I have time), I could do a mass replace of all code and use PHP_VERSION_ID instead.
3. somebody else does the "2."

**Comment by glensc** [comment]
@onlime you may have a better chance with this fork. it's in progress as well, but at least patches have been made, not yet reviewed and merged.

**Comment by onlime** [comment]
> @onlime you may have a better chance with this fork. it's in progress as well, but at least patches have been made, not yet reviewed and merged.

Thanks @glensc - I know about zf1s/zf1 but newer found a simple way to replace [shardj/zf1-future](https://github.com/Shardj/zf1-future) in my two use cases:

- A large project which uses more than a third of all zf1 components: Would I need to specify all single components from zf1s/zf1 as separate Composer requirements?
- ZF1 in a common path for all of my customers on a shared host: Customers require that library dir directly, without using Composer. Cannot tell them to change all their (legacy) projects.

So my question is: How to compile all zf1s/zf1 components into a single library dir? Or how to require all components in Composer? (`composer require zf1s/zend-*` is not supported)

**Comment by glensc** [comment]
@onlime you can install the monrepo as well:

```
composer require zf1s/zf1
```

and you can just download the zip and unpack it:
- https://github.com/zf1s/zf1/releases/latest

**Comment by onlime** [comment]
@glensc Thanks for your detailed instructions! This all makes sense and would be very easy to implement.

But concerning my shared customers, it's impossible to communicate any change here. I definitely cannot tell them to migrate their projects to Composer autoloading, even if it would just be a matter of swapping out a single `require_once` line. I guess most customers that still run their projects on ZF1 have either an outdated deployment process or are just no longer responsible for the project. I cannot introduce any breaking change here. But on the other hand, I can easily recommend them to just fire up `composer require zf1s/zf1` (after a fixed #57) if they are no longer happy with the shared zf1-future code base. I let it be their choice and I don't want to introduce any noise here.

**Comment by glensc** [comment]
@falkenhawk perhaps make a release with the merged code. it's not worse as it is for older PHP versions, and it's definitely something for PHP 8.0.

I don't think I'll work with any of the unfinished pull requests any time soon, and so appears to be for Megatherium.

**Comment by falkenhawk** [comment]
@glensc thank you for your hard work on this so far. Okay I will cut a release in the following days, if time allows. I will also either try myself or ask around if someone could continue working on the unfinished PRs.

**Comment by glensc** [comment]
@falkenhawk how about that release?

**Comment by falkenhawk** [comment]
[Release 1.14.0](https://github.com/zf1s/zf1/releases/tag/1.14.0) is out 🎉
